// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:b_stop/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Departure {
  const Departure({
    required this.id,
    required this.time,
    required this.isNextDay,
    required this.isTimeBasedOnGps,
  });
  final String id;
  final String time;
  final bool isNextDay;
  final bool isTimeBasedOnGps;

  @override
  int get hashCode =>
      id.hashCode ^
      time.hashCode ^
      isNextDay.hashCode ^
      isTimeBasedOnGps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Departure &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          time == other.time &&
          isNextDay == other.isNextDay &&
          isTimeBasedOnGps == other.isTimeBasedOnGps;
}

class Trip {
  const Trip({
    required this.id,
    required this.lineNumber,
    required this.lineName,
    required this.departures,
  });
  final String id;
  final String lineNumber;
  final String lineName;
  final List<Departure> departures;

  @override
  int get hashCode =>
      id.hashCode ^
      lineNumber.hashCode ^
      lineName.hashCode ^
      departures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Trip &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          lineNumber == other.lineNumber &&
          lineName == other.lineName &&
          departures == other.departures;
}
