// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:b_stop/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> setupEnvironmentVariables({required Map<String, String> map}) =>
    RustLib.instance.api
        .crateApiSetupEnvironmentVariablesSetupEnvironmentVariables(map: map);
