// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:b_stop/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_entity`, `from_entity`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

Future<List<TripModel>> tripsForStop({required String stopHash}) =>
    RustLib.instance.api.crateApiTripsTripsForStop(stopHash: stopHash);

class DepartureModel {
  const DepartureModel({
    required this.id,
    required this.time,
    required this.isNextDay,
    required this.isTimeBasedOnGps,
  });
  final String id;
  final String time;
  final bool isNextDay;
  final bool isTimeBasedOnGps;

  @override
  int get hashCode =>
      id.hashCode ^
      time.hashCode ^
      isNextDay.hashCode ^
      isTimeBasedOnGps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DepartureModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          time == other.time &&
          isNextDay == other.isNextDay &&
          isTimeBasedOnGps == other.isTimeBasedOnGps;
}

class TripModel {
  const TripModel({
    required this.id,
    required this.lineNumber,
    required this.lineName,
    required this.departures,
  });
  final String id;
  final String lineNumber;
  final String lineName;
  final List<DepartureModel> departures;

  @override
  int get hashCode =>
      id.hashCode ^
      lineNumber.hashCode ^
      lineName.hashCode ^
      departures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          lineNumber == other.lineNumber &&
          lineName == other.lineName &&
          departures == other.departures;
}
